# Generated by Django 5.2.8 on 2025-12-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='details',
            field=models.BooleanField(default=False),
        ),
    ]
