# Generated by Django 5.2.8 on 2025-11-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_file_message_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at']},
        ),
    ]
