# Generated by Django 5.2.8 on 2025-11-29 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_conversation_options_alter_conversation_user'),
        ('users', '0005_rename_is_staff_user_is_profile_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_form',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Invention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invention_type', models.CharField(choices=[('process', 'Process'), ('product', 'Product'), ('hybrid', 'Hybrid')], max_length=10)),
                ('final_text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='inventions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invention', to='chat.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventions', to='users.user')),
            ],
        ),
    ]
