# Generated by Django 5.2.8 on 2025-11-29 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_conversation_last_form_alter_message_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_history', to='chat.conversation')),
            ],
        ),
    ]
