# Generated by Django 5.2.8 on 2025-11-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_formhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='invention_type',
            field=models.CharField(choices=[('process', 'Process'), ('product', 'Product'), ('hybrid', 'Hybrid')], default='process', max_length=10),
        ),
    ]
